# Generated by Django 5.2.1 on 2025-05-27 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['name'], 'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
    ]
